spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  address: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  address: localhost

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  address: localhost
#3.35.43.15

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common

---